epiverse-trace/tutorials-early

- episodes/read-cases.Rmd
- links.md
- renv/activate.R
- renv/profiles/lesson-requirements/renv.lock
> Early task read

- README.Rmd
- config.yaml
- episodes/clean-data.Rmd
- episodes/data/simulated_ebola.csv
- episodes/describe-cases.Rmd
- episodes/read-cases.Rmd
- episodes/simple-analysis.Rmd
- renv/profiles/lesson-requirements/renv.lock
This pull request re-structure the layout of early tutorials by breaking the episodes into small lessons
> Fix read describe cases

- config.yaml
- renv/profiles/lesson-requirements/renv.lock
fix error workflows in main branch
> temporarily block new episodes

- config.yaml
- episodes/delays-challenges.Rmd
- episodes/delays-functions.Rmd
- episodes/delays-reuse.Rmd
copy of #19 to redirect commits to main and wait for any complementary commits in that branch
review in https://github.com/epiverse-trace/tutorials-early/tree/md-outputs-PR-43
> copy full review upcoming for preliminary merge

- episodes/delays-functions.Rmd
> fix episode on delays-functions and rearrange content

- config.yaml
- episodes/delays-functions.Rmd
- episodes/delays-reuse.Rmd
- renv/profiles/lesson-requirements/renv.lock
These timings will likely have to be adjusted again based on the trial session feedback, but these estimates are already probably more accurate than the current version.
If you already know how to adjust them, feel free to do it directly in this PR.
> Update timings based on training trial schedule

- episodes/clean-data.Rmd
> activate chunk for check dates

- episodes/clean-data.Rmd
This proposal is connected with a suggested assessment from reviewing #95
> remove two tagging to include this in a formative assessment

- episodes/clean-data.Rmd
fix issues previous to full repo review.
Fix #99 
Fix #100 
Fix #115 
Fix #120
> fix format edits

- episodes/describe-cases.Rmd
- episodes/read-cases.Rmd
> remove head function

- learners/setup.md
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix cleanepi installation by adding `"..."` to all package names
* **Other information**:
This also adds an alternative when {pak} does not work for non-epiverse-trace package
> fix pak installation content

- episodes/describe-cases.Rmd
- renv/profiles/lesson-requirements/renv.lock
This PR addresses issue #123. 
Fix #123 
Fix #104
> Fix issue 123

- episodes/data/covid_simulated_data.csv
> add covid data for cleaning

- CITATION.cff
- README.md
rationale: the first author wrote most of the original draft of an episode
> update author order in citation

- episodes/clean-data.Rmd
> replace sys.date to have stable outputs

- episodes/clean-data.Rmd
add challenge to episode to differentiate diagnose vs performing cleaning actions.
The solutions are hidden in the `instructor` callout box.
> add challenge to differentiate diagnose and cleaning functions

- episodes/clean-data.Rmd
Fix #179 
We can also remove the spoiler because the function now generates an output.
> remove assigment to check_date_sequence function

- learners/setup.md
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the issue you are addressing?**
* **If contributing new additional material please explain why you think it is needed**
* **Other information**:
> fix package definition

- learners/setup.md
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the issue you are addressing?**
* **If contributing new additional material please explain why you think it is needed**
* **Other information**:
> use markdown figure format

- learners/setup.md
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the issue you are addressing?**
* **If contributing new additional material please explain why you think it is needed**
* **Other information**:
> add reactable as required by cleanepi print report
